### Criar o primeiro usuário
POST http://localhost:8000/apis/registrar/
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "password123"
}

### Criar o segundo usuário
POST http://localhost:8000/apis/registrar/
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@example.com",
  "password": "password123"
}

### Autenticar o primeiro usuário (Login)
POST http://localhost:8000/apis/login/
Content-Type: application/json

{
  "username": "user1",
  "password": "password123"
}

### Autenticar o segundo usuário (Login)
POST http://localhost:8000/apis/login/
Content-Type: application/json

{
  "username": "user2",
  "password": "password123"
}

### Refresh do token do primeiro usuário
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMzY1NTU0NCwiaWF0IjoxNzMzNTY5MTQ0LCJqdGkiOiJjMmNmOGE2OGVlZDA0Y2FjYTRhZjU1NjhkNTYyNTU1MCIsInVzZXJfaWQiOjF9.afImbY3mqpiKJ9cqhz1kn0CXmc-8FjQI3WIVuyjXRsM
POST http://localhost:8000/apis/token/refresh/
Content-Type: application/json

{
  "refresh": "{{REFRESH_TOKEN}}"
}

### Refresh do token do segundo usuário
@REFRESH_TOKEN2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMzY1NTIxMiwiaWF0IjoxNzMzNTY4ODEyLCJqdGkiOiI0ZTE3MTczYWI1NDY0MDhiYWEzMmFlOGM0NjBiYjBhNyIsInVzZXJfaWQiOjJ9.HkRfGobkvsMgfSPAX4F1tvB6eo9mZAcaAWgwKuznOLY
POST http://localhost:8000/apis/token/refresh/
Content-Type: application/json

{
  "refresh": "{{REFRESH_TOKEN2}}"
}

### Verificar o usuário logado
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNTY5NDYzLCJpYXQiOjE3MzM1NjkxNDQsImp0aSI6IjhkMGI4MDQ2MGZjZjQxYjNhOGUwZjMwYzZlZjIxMDE1IiwidXNlcl9pZCI6MX0.oYSmVlSPtpIQOWbt_xMG2Bc32W44-XziNYwD5_N8MUg
GET http://localhost:8000/apis/usuarios/
Authorization: Bearer {{ACCESS_TOKEN}}

### Listar usuários
GET http://localhost:8000/apis/usuarios/
Authorization: Bearer {{ACCESS_TOKEN}}

### Criar um chamado do primeiro usuário para o segundo
POST http://localhost:8000/apis/chamados/criar/
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "title": "Chamado de teste",
  "description": "Este é um chamado de teste.",
  "receiver": 2
}

### O segundo usuário responde ao chamado
@ACCESS_TOKEN2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNTY5MTQxLCJpYXQiOjE3MzM1Njg4MTIsImp0aSI6IjFhNzUxNDc2NjZmNjQyNWRiNzIyMzM2MDUyNDk3YjU1IiwidXNlcl9pZCI6Mn0.YBO-qXCeSvd9utb6ZzBD-vBGiCD-FIxtmAgSow5Mvvk
POST http://localhost:8000/apis/chamados/1/responder/
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN2}}  # Substitua pelo token do segundo usuário

{
  "content": "Resposta ao chamado de teste."
}

### Listar chamados enviados pelo primeiro usuário
GET http://localhost:8000/apis/chamados/enviados/
Authorization: Bearer {{ACCESS_TOKEN}}  # Substitua pelo token do primeiro usuário

### Listar chamados recebidos pelo segundo usuário
GET http://localhost:8000/apis/chamados/recebidos/
Authorization: Bearer {{ACCESS_TOKEN2}}  # Substitua pelo token do segundo usuário

### Pegar respostas de um chamado
GET http://localhost:8000/apis/chamados/1/respostas/
Authorization: Bearer {{ACCESS_TOKEN}}  # Substitua pelo token do primeiro ou do segundo usuário
